### ISSUE TITLE
'yea' package name

### ISSUE THREAD

**Issue by bttmly** [codeclown/supreme-ajax#1]
I missed your first email about the `yea` npm package name, and I'm not sure how to respond to you directly through their email system. Anyway, happy to relinquish the name, and I responded to npm that I was willing to give it up. Waiting on response from them

**Comment by codeclown** [comment]
Super nice of you, thanks a lot Nick! As you probably noticed, npm did respond and I got the name. I was cc'd on the email thread. All is good on my part, thanks again!

**Comment by bttmly** [comment]
oh awesome, cheers!
